
/**
* The first program*/
// console.log("Hello, World!");
// console.log("I");
// console.log();
// console.log("know");
// console.log();
// console.log("JavaScript");

/**
* The second program*/
// console.log("A cat");
// console.log();
// console.log("says");
// console.log();
// console.log("meow");

/*  Implicit Conversion to String */
// // numeric string used with + gives string type
// let result;
// result = '3' + 2; 
// console.log(result) // "32"
// result = '3' + true; 
// console.log(result); // "3true"
// result = '3' + undefined; 
// console.log(result); // "3undefined"
// result = '3' + null; 
// console.log(result); // "3null"

/* Implicit Conversion to Number */
// // numeric string used with - , / , * results number type
// let result;
// result = '4' - '2'; 
// console.log(result); 
// result = '4' - 2;
// console.log(result); 
// result = '4' * 2;
// console.log(result); 
// result = '4' / 2;
// console.log(result); 

/* Implicit Boolean Conversion to Number */
// // if boolean is used, true is 1, false is 0
// let result;
// result = '4' - true;
// console.log(result); 
// result = 4 + true;
// console.log(result); 
// result = 4 + false;
// console.log(result); 

/* null Conversion to Number */
// // null is 0 when used with number
// let result;
// result = 4 + null;
// console.log(result);  
// result = 4 - null;
// console.log(result);  

/* undefined used with number, boolean or null */
// // Arithmetic operation of undefined with number, boolean or null gives NaN
// let result;
// result = 4 + undefined;
// console.log(result); 
// result = 4 - undefined;
// console.log(result);  
// result = true + undefined;
// console.log(result);  
// result = null + undefined;
// console.log(result);  

/* Convert to Number Explicitly */
// // to convert numeric strings and boolean values to number, you can use Number()
// let result;
// // string to number
// result = Number('324');
// console.log(result); 
// result = Number('324e-1')  
// console.log(result); 
// // boolean to number
// result = Number(true);
// console.log(result); 
// result = Number(false);
// console.log(result); 

//in Js, empty strings and null values return 0
let result1;
result = Number(null);
console.log(result);  
let result2 = Number(' ')
console.log(result);  

/* Non-numeric String Results to NaN */
// // non-numeric string used with - , / , * results to NaN
// let result;
// result = 'hello' - 'world';
// console.log(result); 
// result = '4' - 'hello';
// console.log(result); 

/* var variables */
// var x;
// console.log(x === undefined); // true
// x = 3;
// (function () {
//   var x;
//   console.log(x); // undefined
//   x = "local value";
// })();

/* constant variables*/
// const MY_ARRAY = ["HTML", "CSS"];
// MY_ARRAY.push("JAVASCRIPT");
// console.log(MY_ARRAY); 

/*Boolean primitive*/
// if ([]) {
//     console.log("[] is truthy");
//   }
//   if ([] == false) {
//     console.log("[] == false");
//   }

/* null and undefined primitive*/
// if(null || undefined) {
//     console.log('null is true');
// } else {
//     console.log('null is false');
// }

/* Number primitive*/
// const a = 4 + 9;
// console.log(a); 

/* Number Datatype 1st example*/
// console.log(typeof 12345);
// console.log(10 + 10);
// console.log(10 - 5);
// console.log(10 / 5);
// console.log(10 * 5);
// console.log(10 % 5); //modul
// console.log(2 ** 4); //2 ** 4 calculates 2 raised to the power of 4, which is equivalent to multiplying 2 by itself 4 times.
// console.log(64 ** (1/2)); // 64 ** (1/2) is equal to the square root of 64, which is 8.
// console.log(64 ** 0.5);   // 64 ** 0.5 is equal to the square root of 64, which is 8.

/* Number Datatype 2nd example*/
// let num = 5;
// num++ //num--
// console.log(num++);
// console.log(++num);

/* Number Datatype 3rd example*/
// let num = 10; // 10.10 //output: false
// console.log(Number.isInteger(num)); 
// console.log(Number.parseInt(num));// it can change string to number 
// console.log(typeof parseInt(num));
// console.log(typeof +num); //it change typeof string to number
// console.log(typeof +num.toFixed(2)); // formats the number with two decimal places. qoldiq qismini

/* Number Datatype Math method*/
// console.log(Math.pow(3, 2));
// console.log(Math.sqrt(25));
// console.log(Math.cbrt(64)); //The cube root of 64 is 4, because 4 * 4 * 4 = 64
// console.log(Math.min(20, 45, 2));
// console.log(Math.max(20, 45, 2));
// console.log(Math.abs(-100)); // it returns the positive value of the number regardless of its original sign.
// console.log(Math.random() * 10); // it results random number between 0 and 10
// console.log(parseInt(Math.random() * 10)); //The parseInt() function in JavaScript parses a string and returns an integer. If the number generated by Math.random() * 10 is, for example, 5.23, parseInt() would convert it to 5. This effectively truncates the decimal part.
// console.log(Math.round(10.10));
// console.log(Math.floor(5.5));
// console.log(Math.ceil(10.00011));




/*Bigint/ Big integer primitive */
// Parameter in decimal format
// let bigNum = BigInt(
//     "123422222222222222222222222222222222222");
//     console.log(bigNum);
//     // Parameter in hexadecimal format
//     let bigHex = BigInt("0x1ffffffeeeeeeeeef");
//     console.log(bigHex);
//     // Parameter in binary format
//     let bigBin = BigInt(
//     "0b1010101001010101001111111111111111");
//     console.log(bigBin);
    
/* String Primitive */
// let a = 'hello';
// console.log(a);
// const name = 'My name is "John".';
// console.log(name);

/* symbol primitive */
// let id = Symbol("id");
// let person = {
//     name: "Jack",
//     // adding symbol as a key
//     [id]: 123 
// };
// console.log(person);

/*object non-primitive*/
// const person = { 
//     name: 'John',
//     age: 20
// };
// console.log(typeof person); 

/*declarations var*/
// var x = 1;
// if (x === 1) {
//   var x = 2;
//   console.log(x);
// }
// console.log(x);

/* declaration let */
// let x = 1;
// if (x === 1) {
//   let x = 2;
//   console.log(x);
// }
// console.log(x);

// let login = 'example';
// let password = 'dollar'

/* declaration const*/
// const result = /(a+)(b+)(c+)/.exec("aaabcc");
// const [, a, b, c] = result;
// console.log(a, b, c); 

/*Declaration and initialization -the initializer assigns a value to the variable. In var and let declarations, the initializer is optional. If a variable is declared without an initializer, it is assigned the value undefined*/
// let x;
// console.log(x); // logs "undefined"

/* Functon =>declaration*/ 
// function test(){
//   console.log('Hi');
//   console.log(10 + 10);
// } 
// // invoking calling a function
// test();

/* Functon =>expression or anonymous*/
// let test = function(){    //test is called expression function
//   console.log(10 + 10);
// }
// test();

/* Function => arrow */
// let test = () => {
//   console.log(10 + 10);
// }
// test();

/* function => parametr/argument*/
// function person(name){ //name is parametr
//   return 'John' + ' ' + name
// }
// console.log(person('Special')); //'special' is argument

/* Global Scope */
// program to print a text 
// let a = "hello";
// function greet () {
//     console.log(a);
// }
// greet(); 

/*Function scope*/
// (function foo() {
//     console.log("Hello Foo");
//   })();
  
//   (function food() {
//     console.log("Hello Food");
//   })();
  
//   (() => console.log("hello world"))();
  
  /* Variable hoisting */
//   console.log(x === undefined); 
// var x = 3;
// (function () {
//   console.log(x); 
//   var x = "local value";
// })();

// /* Falsy */
// const match = { teamA: 0, teamB: 1 }
// if (match.teamA){
//   // The following won't run due to the falsy evaluation
//   console.log('Team A: ' + match.teamA);
// }

/*escape line breaks*/
// const str =
//   "this string \
// is broken \
// across multiple \
// lines.";
// console.log(str); 


/* Type conversion: implicit conversion/ explicit conversion*/
// let result;
// result = '3' + 2; 
// console.log(result)
// result = '3' + true; 
// console.log(result);
// result = '3' + undefined; 
// console.log(result);
// result = '3' + null; 
// console.log(result); 


/* Array literals */
// const coffees = ["French Roast", , "Colombian", "Kona"];
// console.log(coffees);


// if(login ==='example' && password === 'dollar'){
//     console.log('Welcome to Instagram');
// }else{
//     console.log('Login or password incorrect');
// }

// function testNum(a) {
//   let result;
//   if (a > 0) {
//     result = 'positive';
//   } else {
//     result = 'NOT positive';
//   }
//   return result;
// }
// console.log(testNum(-5));

/*---------*/
// let fruit = 'apple';
// let kg = 1;


// if(fruit === 'apple'){
//     if(kg === 1){
//         console.log(1000);
//     }else if (kg === 2){
//         console.log(2000);
//     }else {
//         console.log(3000);
//     }
// }else {
//     console.log('unavailable');
// }

// let day = 5;
// switch(day){
//     case 1 : console.log('Monday'); break
//     case 2 : console.log('Tuesday'); break
//     case 3 : console.log('Wednesday'); break
//     case 4 : console.log('Thursday'); break
//     case 5 : console.log('Friday'); break
//     case 6 : console.log('Saturday'); break
//     case 7 : console.log('Sunday'); break
//     default : 'No available';
// }

// switch (undefined) {
//   case console.log(1):
//   case console.log(2):
// }

// const foo = 5;
// switch (foo) {
//   case 2:
//     console.log(2);
//     break; 
//   default:
//     console.log("default");
//   case 1:
//     console.log("1");
// }

// const foo = 1;
// let output = "Output: ";
// switch (foo) {
//   case 0:
//     output += "So ";
//   case 1:
//     output += "What ";
//     output += "Is ";
//   case 2:
//     output += "Your ";
//   case 3:
//     output += "Name";
//   case 4:
//     output += "?";
//     console.log(output);
//     break;
//   case 5:
//     output += "!";
//     console.log(output);
//     break;
//   default:
//     console.log("Please pick a number from 0 to 5!");
// }


// let color = 'black';
// color === 'black' ? console.log('right') : console.log('wrong');
// let age = 19;
// let hasCar = true;
// let citizen = age > 16 || hasCar? 'age available, and has car ' : 'Cannot drive';
// console.log(citizen);

/*------Turnery nullish operator*/
// const name2 = undefined ?? [];
// const name1 = null ?? 'John';
// console.log(name1);

/* throw statement */
// throw "Too big";  // throw a text
// throw 500;        // throw a number
// throw false;      // throw a boolean
// throw person;     // throw an object

/* For loop 1st example*/
// for(let i = 1; i <= 5; i++ ){
//     console.log('JavaScript');
// }

/* for loop 2nd example*/
// let sum = 0;
// const n = 100
// for (let i = 1; i <= n; i++) {
//     sum += i; 
// }
// console.log('sum:', sum);

 /* for loop 3rd example*/
//  let str = 'John Special ';
//  for(let i = 0; i <= str.length - 1; i++){
//     console.log(str[i]);
//  }

// for (let step = 0; step < 5; step++) {
//   console.log("Walking east one step");
// }


/*  for loop 4th example*/
// for(let i = 1; i <= 10; i++){
//     if(i %2 === 0){
//         console.log(i, 'odd number');
//     }else {
//         console.log(i, 'even number');
//     }
// }

// let str = 'John';
// let newStr = '';
// for(let i = 0; i < 10; i++){
//     newStr += str
// }
// console.log(newStr);

/* while loop (varibale outside)*/
// let i = 0;                  //10-from opposite side
// while(i <= 10){             // while(i){
//     console.log(i);         //
//     i++                     //i--
// }

// let n = 0;
// let x = 0;
// while (n < 3) {
//   n++;
//   x += n;
// }
// console.log(n);


/* do while loop(firstly code run and condition false/true) */
// let i = 0;
// do {
//   i += 1;
//   console.log(i);
// } while (i < 5);

/* labeled statement */
// let str = '';
// loop1: for (let i = 0; i < 5; i++) {
//   if (i === 1) {
//     continue loop1;
//   }
//   str = str + i;
// }
// console.log(str);

/* labeled break with for loops*/
// let i, j;
// loop1: for (i = 0; i < 3; i++) {
//   loop2: for (j = 0; j < 3; j++) {
//     if (i === 1 && j === 1) {
//       break loop1;
//     }
//     console.log(`i = ${i}, j = ${j}`);
//   }
// }

/* labeled continue statement*/
// for (let i = 1; i <= 5; i++) { 
//   if (i == 3) {
//       continue;
//   }

//   console.log(i);
// }

/* nested loop*/
// for(let i = 0; i <= 2; i++){
//     console.log('--outside loop');
//     for(let j = 0; j <= 3; j++){
//         console.log('-------inner loop');
//     }
// }


/* let */
// let x = 1;
// if (x === 1) {
//   let x = 2;
//   console.log(x);
// }
// console.log(x);

/* return statement */ 
// function getRectArea(width, height) {
//   if (width > 0 && height > 0) {
//     return width * height;
//   }
//   return 0;
// }
// console.log(getRectArea(3, 4));
// console.log(getRectArea(-3, 4));

// function counter() {
//   for (let count = 1; ; count++) {
//     console.log(`${count}A`); 
//     if (count === 5) {
//       return;
//     }
//     console.log(`${count}B`); 
//   }
//   console.log(`${count}C`); 
// }
// counter();

